language: node_js
node_js: stable

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    branch: master
